### ISSUE TITLE
update version number of python extension from 4.5.0 to 4.6.0?

### ISSUE THREAD

**Issue by armijnhemel** [trendmicro/tlsh#102]
In several files of the Python extension the version is still set to 4.5.0:

```
$ grep -r 4.5.0 py_ext/
py_ext/pypi_package/README.md:## What's new in py-tlsh 4.5.0
py_ext/pypi_package/setup.py:    version="4.5.0",
py_ext/pypi_package/PKG-INFO:Version: 4.5.0
py_ext/pypi_package/PKG-INFO:	## What's new in py-tlsh 4.5.0
py_ext/setup.py:    version = '4.5.0',
py_ext/tlshmodule.cpp:#define TLSH_VERSION "4.5.0"
```

I don't know if this has will have any impact on functionality, but possibly it is something you want to address.

**Comment by jonjoliver** [comment]
I will release an updated package at https://pypi.org/project/py-tlsh/

**Comment by jonjoliver** [comment]
Thank you.
I combined this with a pull request
I created a new Python package and updated this repo
Please check at
    https://test.pypi.org/project/py-tlsh/4.7.0/
To install use
    $  pip install -i https://test.pypi.org/simple/ py-tlsh==4.7.0

**Comment by jonjoliver** [comment]
Version 4.7.2 is now at https://pypi.org/project/py-tlsh/
It is working for me.
I added further Python Regression tests

So I am closing.
Please re-open if it is not working for you.
