### ISSUE TITLE
tagging releases

### ISSUE THREAD

**Issue by armijnhemel** [trendmicro/tlsh#106]
Would it perhaps be possible to properly tag releases in the future? I can see that there is a release 4.7.2 but there is no corresponding tag.

**Comment by jonjoliver** [comment]
Sorry - I will do so in future

**Comment by jonjoliver** [comment]
Hi Armijn

4.7.2 was mainly a Python upgrade / new library
We had quite a few tricky Python issues (#95 #96 #98 #102 #105) which were about Python versions and environments.
I asked people to check those versions.
It appears that 4.7.2 is stable and working
I will now add it as a production release and tag it
Sorry for the delay - I should have circled back earlier!
:-)

Cheers
jono

**Comment by jonjoliver** [comment]
should be all good now

**Comment by ambroisie** [comment]
You seem to have forgotten to tag for version 4.10.0, if you could please add it :-).

**Comment by jonjoliver** [comment]
Thanks
