### ISSUE TITLE
missing git release tags

### ISSUE THREAD

**Issue by anthraxx** [trendmicro/tlsh#11]
Hey, first: thanks for this great tool.

I wanted to ask if it would be possible to push git tags for released versions. It seems that you do proper versioning of the tool (according to the Changelog and CMakeLists.txt) but never push the git tags to those commits "releasing" a new version.

It would make my life lot easier packaging your software for a distribution and keeping track of new released updates. Would highly appreciate if you push tags that you also keep them in sync in the future

sincerely,
anthraxx

**Comment by Scott4man** [comment]
Hi,

Glad you are finding Tlsh useful.

I have labeled versions v3.4.0 and v3.4.1 and pushed them to
https://github.com/trendmicro/tlsh.  Let me know if you need any previous
versions tagged.

When you include the Tlsh software in your distribution, please include a
NOTICE file, similar to the following:
https://github.com/triplecheck/TLSH/blob/master/NOTICE.txt.

Sincerely,
Scott

**Comment by anthraxx** [comment]
@Scott4man cool, thanks a lot :+1:
From my point of view, thats totally fine and enough...

If you keep them in sync for future releases that would be awesome, I'm packaging 3.4.1 now and have setup upstream watched onto the github tags to be notified about updates... thanks again :smile:

**Comment by jonjoliver** [comment]
done.
I made version 3.9.2 a release
