### ISSUE TITLE
windows10 x64 installed error.

### ISSUE THREAD

**Issue by fifysky** [trendmicro/tlsh#118]
I try many ways to solve the error，but no luck.I have installed VC++2015(14.0).
pls help me.
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

**Comment by jeremyng123** [comment]
I got the same error. i saw there was another issue and supposed to be fixed by using py-tlsh, however, i got the same error... pls assist!

**Comment by jeremyng123** [comment]
> I try many ways to solve the error，but no luck.I have installed VC++2015(14.0). pls help me. error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

i found the solution!! you gotta install MFC. Go Visual Studio Build Tools and install C++ MFC for latest v142 build tools.

**Comment by fifysky** [comment]
> 

Thanks bro, I solve the issue through install the latest VS version.

**Comment by 12mik12** [comment]
Hello all, I have the exact same issue, however, no matter what I try it just doesn't work. 
I enabled MFA for latest 142 build tools for x64 and x86, i enabled C++ in VS, etc. etc. but i still get this error :((((
