### ISSUE TITLE
all tests failing on build

### ISSUE THREAD

**Issue by anthraxx** [trendmicro/tlsh#12]
Any idea why the tests are failing or how to easily debug it? Are the tests working on your machine?

    
    Running tests...
    Test project /build/tlsh-3.4.1/build/release
        Start 1: tlsh_unittest_len
    1/2 Test #1: tlsh_unittest_len ................***Failed    0.31 sec
        Start 2: tlsh_unittest_xlen
    2/2 Test #2: tlsh_unittest_xlen ...............***Failed    0.17 sec
    
    0% tests passed, 2 tests failed out of 2
    
    Total Test time (real) =   0.48 sec
    
    The following tests FAILED:
    	  1 - tlsh_unittest_len (Failed)
    	  2 - tlsh_unittest_xlen (Failed)
    Errors while running CTest
    Makefile:72: recipe for target 'test' failed
    make: *** [test] Error 8

**Comment by Scott4man** [comment]
It passes on the MAC but not on Linux.

Let me investigate and get back to you.  I will also update the README file
with how to debug.

Scott

**Comment by Scott4man** [comment]
It has to do with my change to the test.sh script to test the python
extension.

If you have not built and installed the python extension, then test.sh will
fail.

I will back out the python extension test, and will add a message that the
python extensions should be tested after changes.

Let me know if you have any other problems.

**Comment by anthraxx** [comment]
Okay the regular non-python tests seem working if I remove the python related changes in the test.sh.

related to the python tests:
It would be great if its not required to have the extension already installed to run the test, that is not the optimal solution. A better way would be to use some shell construct like PYTHONPATH=".:${PYTHONPATH}" to prepend the current dir (assuming current dir is relative to the python extension) so the tests can run in-place and just *after* the tests are passing, one can install the extension into the system.

**Comment by Scott4man** [comment]
I checked in changes to fix this, and I bumped the version number to 3.4.2

**Comment by anthraxx** [comment]
hm I don't think its getting into the right direction... with the new 3.4.3 now no tests are run at all automatically.

the call to 'make test' does nothing:
    
    make: Nothing to be done for 'test'.
    
I have to invoke './Testing/test.sh' myself, which should be done automatically via some make targets.
Also the nice overview telling "100% tests passed, 0 tests failed out of 2" is gone, invoking the shell-script directly just create lot of output with 2x 5 tests running and saying "passed" in a new line.

Also my major concern is still open: One should not need to install the python bindings in order to run the tests... thats pretty much point less for a test. Especially from a point of view of a package creator, this is a no-go. A test should determine if the current version is properly working _before_ it gets installed into the system.
Please look up the PYTHONPATH env var that can be used so you can import tlsh locally without the need to install it into the system.

As mentioned, I would like to package this software for a distribution and its not an option to run tests _after_ packaging and installation, it has to work _before_ creating the final packages.

**Comment by anthraxx** [comment]
Additionally, would it be possible to make this library functional for python3?
The python2 tests are running fine and seem to work, however if I invoke it with python 3, I get a ValueError:
(without looking it up, but I assume its because of python3 bytes())

**python3:**
    
    # python test.py ../Testing/example_data/2005NISSE.txt ../Testing/example_data/1english-only.txt
    tlsh.hash hex1 06D29517F780237185070293B60E36FAB735C0F833D66460688DA22D6756E751B7BAEB
    tlsh.hash hex2 E951784702042376169012B1BA5A76EAF36092FC3311A595B4856235278F9F973763EF
    tlsh.diff(hex1, hex2) 427
    tlsh.diff(hex2, hex1) 427
    tlsh.Tlsh hex1 06D29517F780237185070293B60E36FAB735C0F833D66460688DA22D6756E751B7BAEB
    tlsh.Tlsh hex2 E951784702042376169012B1BA5A76EAF36092FC3311A595B4856235278F9F973763EF
    h1.diff(h2) 427
    h2.diff(h1) 427
    h1.diff(hex2) 427
    h2.diff(hex1) 427
    Traceback (most recent call last):
      File "test.py", line 39, in <module>
        h3.fromTlshStr(hex2)
    ValueError: argument is not a TLSH hex string
