### ISSUE TITLE
There is a memory leak in py-tlsh 

### ISSUE THREAD

**Issue by qiyeboy** [trendmicro/tlsh#125]
vpObj1 = tlsh.Tlsh()
vpObj1.fromTlshStr(tlsh_str)

fromTlshStr ，This function cannot release memory when called frequently, causing the memory to be completely occupied

**Comment by jonjoliver** [comment]
Hi qiyeboy

I left Trendmicro just over 2 years ago. I am jumping in here to help out as best I can.
Let me see if I can reproduce.
If I find the bug, then I will fix and update version at py-tlsh

Cheers jono

**Comment by merces** [comment]
Fixed by #137.
