### ISSUE TITLE
tlsh segfault on large directory

### ISSUE THREAD

**Issue by elsif2** [trendmicro/tlsh#16]
TLSH version: 3.4.5 compact hash, 1 byte checksum

Directory contains 230,781 files. The system has 64GB of memory.

$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 20
file size               (blocks, -f) unlimited
pending signals                 (-i) 516130
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 999999
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 516130
virtual memory          (kbytes, -v) 9999999999
file locks                      (-x) unlimited

$ ./bin/tlsh_unittest -r /mnt/data
Segmentation fault

strace info:
```
mmap(NULL, 852165308416, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
brk(0xc66ab4c000)                       = 0x1b22000
mmap(NULL, 852165439488, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
mmap(NULL, 134217728, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x7f403d0fd000
munmap(0x7f403d0fd000, 49295360)        = 0
munmap(0x7f4044000000, 17813504)        = 0
mprotect(0x7f4040000000, 135168, PROT_READ|PROT_WRITE) = 0
mmap(NULL, 852165308416, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
```

gdb info:

Program received signal SIGSEGV, Segmentation fault.
0x0000000000401bfa in recursive_read_files_from_dir(char*, FileName*, int, int*) ()

Questions:

1) Can this error condition be handled gracefully?
2) Can the memory limit be raised?

**Comment by elsif2** [comment]
Using the c++ memory model at ~line 269 and ~345 in tlsh_unittest.cpp appears to fix the issue:

```

269,271c269
< 				//fnames[*n_file].name = strdup(tmp_fname);
< 				fnames[*n_file].name = new char[strlen(tmp_fname)+1];
< 				strcpy(fnames[*n_file].name, tmp_fname);

345,346c343
< 	//fnames = (struct FileName *) calloc ( max_files+1, sizeof(struct FileName) * (max_files+1) );
< 	fnames = (struct FileName *) new struct FileName[max_files+1];
```

**Comment by Scott4man** [comment]
Using the c++ memory model will require using delete instead of free in function freeFileName()

**Comment by vichargrave** [comment]
This issue was solved with pull request https://github.com/trendmicro/tlsh/pull/22.
