### ISSUE TITLE
Java version of TLSH

### ISSUE THREAD

**Issue by nunobrito** [trendmicro/tlsh#2]
Dear developers,

I've made available a Java version of the TLSH algorithm that you find at https://github.com/triplecheck/TLSH

In essence, the relevant code that performs the hashing is found inside a single Java source code file at https://github.com/triplecheck/TLSH/blob/master/sources/TLSH.java

Please verify if due credits are provided and/or if any correction is necessary. The main() method contains usage examples. To apply in other Java projects one just needs to copy TLSH.java into the target project.

Performance-wise, running on our experiments the code was useful for outputting an average of 200 million hashes/day for a sub-set of files in our archive. (Pentium i7, 4 cores).

-- Nuno

**Comment by Scott4man** [comment]
Hi Nuno,

I am a developer working at Trend Micro, Inc., under Jon Oliver, who is the lead author of the TLSH algorithm.

First of all, sorry for the delay in getting back to you.

Second of all, thank you for your work on porting TLSH to Java!

I have downloaded your code and verified that running the main function in TLSH.java generates the same results as our simple_unittest executable.   Nice work!

For more complete testing, we have regression tests for TLSH, which depend upon:

  *   The executable tlsh_unittest (https://github.com/trendmicro/tlsh/blob/master/test/tlsh_unittest.cpp).
  *   A framework for running tlsh_unittest (https://github.com/trendmicro/tlsh/blob/master/Testing/test.sh).

The expected outputs for the regression tests can be found under https://github.com/trendmicro/tlsh/tree/master/Testing/exp.  For your implementation, which uses a checksum value of 1 and a EFF_BUCKETS value of 128, the expected output file names would be those that start with "example_data.128.1.".

Do you have the time, and would you be interested in implementing tlsh_unittest and a framework (e.g. JUint) to run the regression tests?

Best Regards,

Scott Forman

<table class="TM_EMAIL_NOTICE"><tr><td><pre>
TREND MICRO EMAIL NOTICE
The information contained in this email and any attachments is confidential 
and may be subject to copyright or other intellectual property protection. 
If you are not the intended recipient, you are not authorized to use or 
disclose this information, and we request that you notify us by reply mail or
telephone and delete the original message from your mail system.
</pre></td></tr></table>

**Comment by nunobrito** [comment]
Hi Scott,

Sounds good, I'd be happy to add regression tests.

If there is no inconvenient, I'll create a JUnit test case and write similar tests where applicable. On this case the main difference is the fact that this Java port doesn't come with a command line option since it was intended to be used as library. In case there is enough interest, it is possible to add command line support, or at least we can add the basic model that you can further expand to match the original code (if intended).

Please permit some time to implement the regression tests as we are currently completing other code implementations on our queue. I'll likely have questions and will ask them when working on this topic.

Thanks,
Nuno

**Comment by Scott4man** [comment]
Tlsh Java version available at https://github.com/triplecheck/TLSH
