### ISSUE TITLE
tlsh-3.4.5/utils/rand_tags.cpp:369: possible bad if statement ?

### ISSUE THREAD

**Issue by dcb314** [trendmicro/tlsh#20]
tlsh-3.4.5/utils/rand_tags.cpp:369:42: warning: ordered comparison of pointer with integer zero [-Wextra]

Source code is

   if ((*ntags <= 0) && (ndistinct_tags <= 0))
        return;

Maybe better code

   if ((*ntags <= 0) || (*ndistinct_tags <= 0))
        return;

**Comment by vichargrave** [comment]
Not quite.  I think it should be:

if ((*ntags <= 0) && (*ndistinct_tags <= 0))
    return;

ntags and ndistinct_tags are pointers.

**Comment by vichargrave** [comment]
Fixed
