### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [trendmicro/tlsh#21]
I would like to point out that an identifier like "[`_TLSH_H`](https://github.com/trendmicro/tlsh/blob/dca4a416a31512014b3de33e66a757b99f0395b5/include/tlsh.h#L19)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jonjoliver** [comment]
I changed all the header files to use
HEADER_TLSH_H
instead of
_TLSH_H

so now they do not start with an underscore
(as per the new naming convention you refer to)

**Comment by elfring** [comment]
How do you think about to replace the prefix “`HEADER`” with [a kind of UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier "Description for the usage of universally unique identifiers")?

**Comment by jonjoliver** [comment]
Hi

I got the syntax "HEADER_" from Compliant Solution example at
https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier.

Cheers jono

**Comment by elfring** [comment]
The currently selected name pattern is fine for the mentioned coding style compliance.
Would you like to [make the affected include guards also a bit more unique](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Selection of safe idenitifiers for include guards")?
