### ISSUE TITLE
Building Python ext in Windows: vcvarsall.bat

### ISSUE THREAD

**Issue by ross-spencer** [trendmicro/tlsh#27]
Currently getting this issue:

```
C:\Working\git\tlsh>cd py_ext

C:\Working\git\tlsh\py_ext>python setup.py build
running build
running build_ext
building 'tlsh' extension
error: Unable to find vcvarsall.bat
```

Just following the tips here: https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/ if there is something i can do in future i'll try and contribute, but it looks unlikely in the short term with other deadlines to reach. 

Will return to my Linux terminal for now.

**Comment by jonjoliver** [comment]
sorry I do not have a Windows version of Python environment to test this

I just fixed a problem with the Python extension in Linux
So could you retest it - the issue may be resolved...

**Comment by ross-spencer** [comment]
Great stuff!

I can test the windows version next week if someone doesn't get there first, will let you know how it goes.

**Comment by tinazone** [comment]
hi
I still have this problem on windows, can you help me?I'v installed visual studio 2019 but it didn't fix
