### ISSUE TITLE
Issue creating python extension of tlsh library

### ISSUE THREAD

**Issue by NirmalVats** [trendmicro/tlsh#28]
Hi ,

I am following steps mentioned in README to get tlsh on my centos 6.5 machine.
Installed cmake and done with running make.sh gracefully.

But when i try to execute  -> python setup.py build, to build python extension, it gives below errors.

running build
running build_ext
building 'tlsh' extension
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data/tlsh-master/include -I/usr/local/include/python3.4m -c tlshmodule.cpp -o build/temp.linux-x86_64-3.4/tlshmodule.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
tlshmodule.cpp:169: warning: missing braces around initializer for ‘PyObject’
tlshmodule.cpp: In function ‘PyObject* Tlsh_fromTlshStr(tlsh_TlshObject*, PyObject*)’:
tlshmodule.cpp:226: error: ‘TLSH_STRING_LEN’ was not declared in this scope
tlshmodule.cpp: In function ‘PyObject* Tlsh_update(tlsh_TlshObject*, PyObject*)’:
tlshmodule.cpp:253: error: ‘MIN_DATA_LENGTH’ was not declared in this scope
tlshmodule.cpp: In function ‘PyObject* Tlsh_final(tlsh_TlshObject*)’:
tlshmodule.cpp:269: error: ‘MIN_DATA_LENGTH’ was not declared in this scope
tlshmodule.cpp: In function ‘PyObject* Tlsh_hexdigest(tlsh_TlshObject*)’:
tlshmodule.cpp:281: error: ‘TLSH_STRING_LEN’ was not declared in this scope
tlshmodule.cpp:287: error: ‘hash’ was not declared in this scope
tlshmodule.cpp: In function ‘PyObject* Tlsh_diff(tlsh_TlshObject*, PyObject*)’:
tlshmodule.cpp:321: error: ‘TLSH_STRING_LEN’ was not declared in this scope
error: command 'gcc' failed with exit status 1

Kindly assist, if i am missing some dependencies or something.
Thanks in advance.

**Comment by vichargrave** [comment]
We are currently trying to sort out that issue.

Thanks for your patience.

**Comment by NirmalVats** [comment]
Hi vichargrave,
Thanks for looking upto this matter. Kindly let me know if you found any solution.

**Comment by jonjoliver** [comment]
Hi NirmalVats

I believe that I have resolved the issue

cheers
jono

**Comment by NirmalVats** [comment]
Thanks a ton.
Working fine now.
