### ISSUE TITLE
how to use -force option in python

### ISSUE THREAD

**Issue by lingcheng99** [trendmicro/tlsh#29]
I read TLSH version 3.5.1 has a force option to use string length 50 instead of 256. I am working with shorter texts and this option would be very useful. But I cannot figure out how to use it in python API. Any ideas?

**Comment by jonjoliver** [comment]
I will have to add it to the python API

**Comment by jonjoliver** [comment]
done

**Comment by abhyuday07** [comment]
How to use the feature?

**Comment by jonjoliver** [comment]
Abhyuday Pandey asked "How to use the feature?"

There is a regression test that shows you.
From python_test.sh
<PRE>
echo
echo "testing the -force option for short strings..."
echo
for file in small small2 ; do
        echo                    "${PYTHON} ../py_ext/tlsh_digest.py -force example_data/$file.txt > $TMP/py_$file.tlsh"
                                 ${PYTHON} ../py_ext/tlsh_digest.py -force example_data/$file.txt > $TMP/py_$file.tlsh
        echo "diff $TMP/py_$file.tlsh exp/$file.tlsh_EXP"
              diff $TMP/py_$file.tlsh exp/$file.tlsh_EXP
        if [ $? -ne 0 ]; then
                echoerr "error: diff $TMP/py_$file.tlsh exp/$file.tlsh_EXP"
                popd > /dev/null
                exit -1
        fi
done

So the Python script tlsh_digest.py has a command line option -force.
You can do
$ python tlsh_digest.py -force file.dat
where file.dat is the file you wish to hash
and tlsh_digest.py is the script in the py_ext directory
</PRE>

**Comment by jonjoliver** [comment]
Hi

See my answer in
https://github.com/trendmicro/tlsh/issues/29

Cheers
jono
