### ISSUE TITLE
Python type error

### ISSUE THREAD

**Issue by RussBaz** [trendmicro/tlsh#3]
I am using Python 3.4.2 on Ubuntu 14.10 and I am getting the following error when executing this script:

```python
import tlsh

data = "hello"
print(tlsh.hash(data))
```
```python
Traceback (most recent call last):
  File "script.py", line 4, in <module>
    print(tlsh.hash(data))
TypeError: must be impossible<bad format char>, not str
```
Could you explain how to fix this issue?

**Comment by Scott4man** [comment]
Hi,

The minimum string length is 512 bytes.  

Please try with a longer string.

Regards,

Scott Forman

**Comment by Scott4man** [comment]
I will also update the README file to document the minimum string length, and will see if we can exit more gracefully.

**Comment by RussBaz** [comment]
Thanks for the reply. I tried much larger data this time but there was still an error.

```python
import sys

import tlsh
import requests

r = requests.get('http://reddit.com')
data = r.text
print('URL: {}'.format(r.url))
print('Status code: {}'.format(r.status_code))
print('Number of bytes: {}'.format(sys.getsizeof(data)))
print('Number of characters: {}'.format(len(data)))
print(tlsh.hash(data))
```
It results in the following error:
```python
URL: http://www.reddit.com/
Status code: 200
Number of bytes: 225062
Number of characters: 112494
Traceback (most recent call last):
  File "script.py", line 12, in <module>
    print(tlsh.hash(data))
TypeError: must be impossible<bad format char>, not str
```
However, I looked into the py_ext/tlshmodule.cpp and found the following part of hash_py function:
```cpp
  if (!PyArg_ParseTuple(args, "t#", &pBuffer, &len)) {
    return NULL;
  }
```
Changing input format to "s#" fixed the problem for me.
```cpp
  if (!PyArg_ParseTuple(args, "s#", &pBuffer, &len)) {
    return NULL;
  }
```
I tested this with Python 3.4.2 and Python 2.7.8. It worked in both cases. (Though, Python 2.7.8 required some messing around with an encoding) I will push a patch now. Please verify that this patch is not breaking anything. And thank you very much for your replies.

**Comment by RussBaz** [comment]
Oops, github declined my new branch.
