### ISSUE TITLE
TLSH_CHECKSUM_LEN  MIN_DATA_LENGTH

### ISSUE THREAD

**Issue by Z000000** [trendmicro/tlsh#33]
how i config the argv like this  i find many argv which i do not know the value of them    you should provide one header file for  configing  them

**Comment by jonjoliver** [comment]
type in
    $ tlsh
to get the usage

$ tlsh

usage: tlsh [-c <file|digest>]         -f <file>     [-T <threshold_value>] [-xlen] [-force] [-details]
     : tlsh  -c <file|digest>          -d <digest>   [-T <threshold_value>] [-xlen] [-force] [-details]
     : tlsh [-c <file|digest> | -xref] -r <dir>      [-T <threshold_value>] [-xlen] [-force] [-details]
     : tlsh [-c <file|digest> | -xref] -l <listfile> [-T <threshold_value>] [-xlen] [-force] [-details]
     : tlsh -version: prints version of tlsh library

tlsh can be used to compute TLSH digest values or the distance between digest values in the following ways:
  1) To compute the TLSH digest value of a single file (-f file), or a directory of files (-r dir).
     This output can be used to create the listfile required by the -l option described below.
  2) To compute the distance between a comparison file or TLSH digest (-c file|digest) and the
     specified file (-f file), TLSH digest (-d digest), directory of files (-r dir), or list (-l listfile).
  3) To compute the distance between each element in a set of files (-r dir) or files/digests in a
     list (-l listfile) with every other element in that set, using the –xref flag

parameters: 
  -c file|digest:     Specifies a filename or digest whose TLSH value will be compared to a specified TLSH digest (-d) OR the TLSH value of a sepcified
                      file (-f) OR the TLSH values of files in a specified directory (-r) OR the TLSH values in a specified listfile (-l)
  -xref:              Used only when a set of files (-r dir) or TLSH values (-l listfile) is specified.
                      Results in the calculation of distance between each element in the set.
  -f file:            Specifies a file whose TLSH values are to be computed, or used for comparison (-c file|digest)
  -d digest:          Specifies a TLSH digest value that is to be compared to the specified comparison file or digest (-c file|digset)
  -r dir:             Specifies a recursive directory search for files whose TLSH values are to be computed, or used for comparison (-c file|digset or -xref)
  -l listfile:        Used for comparison purposes only (-c file|digset or -xref).  Each line in listfile can contain either:
                      - a TLSH digest value (comparison output will display TLSH digests)
                      - a tab separated TLSH digest value and its corresponding filename (comparison output will display filenames)
                      The tab separated listfile can be generated by running tlsh with either the -f or -r flag
  -xlen:              Passed as the len_diff parameter to Tlsh::totalDiff().  If not specified, len_diff will be true, else false.  Determines if the lengths
                      of the compared files is to be included in determining the distance.  See tlsh.h for details.
  -force:             Force a digest to be created even when the input string is as short as 50 characters.
  -details:           Results in extra detailed output.
  -T threshold_value: Used only during comparisons (-c file|digset or -xref).  Specifies the maximum distance that a comparison must
                      generate before it is reported. (defaults to 9999)

Restrictions:
  The input string to create a TLSH digest should be >= 256 characters
  If the -force option is used - then the string can be as short as 50 characters

Example usages:
  To calculate the distance between two files, run the command:
     tlsh -c <file 1> -f <file 2>

  To calculate the distance between two TLSH digest values, run the command:
     tlsh -c <TLSH digest 1> -d <TLSH digest 2>

  To calculate the TLSH digest values for every file in a directory - this can create the input for the -l option
     tlsh -r <dir>

  To get the distance between a reference TLSH digest value, and a list of TLSH digest values in a file:
     tlsh -c <TLSH digest> -l <file>

  To compare the TLSH value for every file in a directory, to every other file in that directory, run the command:
     tlsh -xref -r <dir>

**Comment by jonjoliver** [comment]
I hope this helped
I am closing - repost it if you need more information
