### ISSUE TITLE
Can't import 'python-tlsh'

### ISSUE THREAD

**Issue by soimsoim** [trendmicro/tlsh#34]
After I install the 'python-tlsh', I can't import 'tlsh' in python.

How I install 'python-tlsh'
- https://www.devmanuals.net/install/ubuntu/ubuntu-16-04-LTS-Xenial-Xerus/how-to-install-python-tlsh.html

$ dpkg -L python-tlsh
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/python-tlsh
/usr/share/doc/python-tlsh/copyright
/usr/share/doc/python-tlsh/changelog.Debian.gz
/usr/lib
/usr/lib/python2.7
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/tlsh.x86_64-linux-gnu.so
/usr/lib/python2.7/dist-packages/tlsh-0.2.0.egg-info

$ python -c 'import tlsh'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tlsh

How can I import 'python-tlsh'?

**Comment by jonjoliver** [comment]
Hi soimsoim

I was unaware of that page and the Ubuntu installation method described there.
One thing struck me - I did not see the compilation of the C++ code.

Did you see the README.python ?
https://github.com/trendmicro/tlsh/blob/master/README.python

Have you tried the following ?
1. downloading https://github.com/trendmicro/tlsh
2. cd tlsh
3. ./make.sh
4. follow the instructions in README.python

I have not tested that on Ubuntu - and if it has troubles - then I will try to find access to Ubuntu

Cheers
jono

**Comment by soimsoim** [comment]
There is no error as I follow the way you gave me.
Thanks a lot.

**Comment by jonjoliver** [comment]
thanks
closing issue
