### ISSUE TITLE
check for negative pointer

### ISSUE THREAD

**Issue by 0-wiz-0** [trendmicro/tlsh#38]
In `utils/rand_tags.cpp`, the pointer `ndistinct_tags` is checked if its negative or zero:
````
static void rhtml_contents(std::string &htmls, int *ntags, int *ndistinct_tags)
{
       if ((*ntags <= 0) && (ndistinct_tags <= 0))
````
Perhaps it should be compared with `== NULL` instead?

**Comment by jonjoliver** [comment]
fixed - Thanks! :-)
jono

**Comment by jonjoliver** [comment]
I just found the fix broke a regression test that generated random HTML content for testing purposes
