### ISSUE TITLE
support for input less than 256 bytes

### ISSUE THREAD

**Issue by mauvew** [trendmicro/tlsh#52]
Does tlsh only support input longer than 256 bytes? As 256 bytes is fairly large amount of chars, does it support short sentences like "hello world, hello cat, hello dog" as the input string?

**Comment by jonjoliver** [comment]
Thanks
I hope the changes to README clarified the issue

**Comment by mauvew** [comment]
Thanks a lot for the clarification.

Just wondering if using the force mode, will it affect the precision and performance?

**Comment by jonjoliver** [comment]
No charge to the string generation algorithm
Or the distance function.

The only change of the force option is to reduce the lower limit from 256 bytes to 50 bytes
