### ISSUE TITLE
version-specific tlsh solution files not found for Windows

### ISSUE THREAD

**Issue by TakahiroHaruyama** [trendmicro/tlsh#58]
I can't find version-specific tlsh solution files as the setup instruction shows. 
How can I use it on Windows?

**Comment by jonjoliver** [comment]
Have you looked at the CMakefile in the Windows directory?

**Comment by TakahiroHaruyama** [comment]
Thanks, I built the Windows 32-bit binaries but couldn't make x64 ones:

fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'

Where should I modify the file? Thanks

**Comment by jonjoliver** [comment]
I'm guessing your machine is Windows-32
Is that correct?
So you want to build a 64 bit code on a 32 bit machine. I think cmake can do that but it might be fiddly.
Maybe easier to build windows-64 binaries on a 64 bit machine.

Or have I missed something / made incorrect assumptions (quite possible)...

**Comment by TakahiroHaruyama** [comment]
Sorry for delay and thanks. I sent an email to the address.

**Comment by jonjoliver** [comment]
TakahiroHaruyama: Can you check this release in your environment?

**Comment by jonjoliver** [comment]
We tested it in our environment - works

So if anyone has a reasonably standard Windows environment - and it does not work - then please reopen this issue
