### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by rhaist** [trendmicro/tlsh#60]
I would like to bring up #11 again to highlight the need for release tags for every stable release.
If you don't tag your releases linux distribution package maintainers will not be aware of updates and this results in old versions of tlsh being shipped to all users.

Eg. Debian Buster is now in freeze and will ship with tlsh 3.4.4:
https://packages.debian.org/buster/tlsh-tools

**Comment by jonjoliver** [comment]
done.
I made version 3.9.2 a release
