### ISSUE TITLE
How to compute the distance for two hash strings C++

### ISSUE THREAD

**Issue by VISWESWARAN1998** [trendmicro/tlsh#68]
Using the C++ library I have calculated two hashes and assigned it to strings like,

```c++
std::string hash1 = "5582932E7B4443F206C202A16A4F6CDFE32AD5B9722E11542859C15D236FE35C3BFAD9";
std::string hash2 = "C782932E7B4443F205C203A16A4B6CDFE32AD4BDB23A11546859C15D236BE35C3BFAD9";
```

What methods do Tlsh offers to find the distance score between two hashes could any one help me with this issue.

**Comment by jonjoliver** [comment]
Look at timing_unittest.cpp
That shows you how to do it
https://github.com/trendmicro/tlsh/blob/master/test/timing_unittest.cpp

**Comment by VISWESWARAN1998** [comment]
Hello thank you for your communication, I was able to see a method named "totalDiff" something like this,

```c++
int dist = t1.totalDiff(&t2);
```

But is used to calculate the distance between two Tlsh objects not for two hashes of Tlsh strings generated from "getHash" method.

Am I missing something could you please help me with this issue. Thank you so much!

**Comment by jonjoliver** [comment]
Tlsh t1;
Tlsh t2;
int err1;
int err2;
    err1 = t1.fromTlshStr(hash1.cstr());
    err2 = t2.fromTlshStr(hash2.cstr());
    if (err1 || err2) {
          // error condition
          ...
    }
          int dist = t1.totalDiff(&t2);
          ...
    }

**Comment by VISWESWARAN1998** [comment]
Thank you very much sir!
