### ISSUE TITLE
Python TypeError on example?

### ISSUE THREAD

**Issue by Nirusu** [trendmicro/tlsh#71]
I cloned the repo, built and installed the Python extension and tried the example.

The README says: 

> For example, tlsh.hash(str(os.urandom(256))), should always generate a hash.

Now, I wrote this tiny script:

```
import tlsh
import os

hash = tlsh.hash(str(os.urandom(256)))
print(hash)
```
And instead of "always generating a hash", it always generates this sweet TypeError for me:
``` python3 test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    hash = tlsh.hash(str(os.urandom(256)))
TypeError: a bytes-like object is required, not 'str' 
```
Removing the str works and generates a hash for me, but yeah, this isn't exactly how the README says it should work. Perhaps someone forgot to update the readme?

Runtime is Python 3.6.8 (64-Bit) on Ubuntu 18.04.

**Comment by jonjoliver** [comment]
I have removed the str()
And added comments that you most process a byte string

You can see these improvements in the new python package at
https://pypi.org/project/py-tlsh/
