### ISSUE TITLE
Request to add a new Java port of TLSH

### ISSUE THREAD

**Issue by kevemueller** [trendmicro/tlsh#87]
To whom it may concern, 
I have taken a fresh look at porting TLSH to the Java language. My result is published under [https://github.com/kevemueller/kTLSH](https://github.com/kevemueller/kTLSH).
I would appreciate being referenced in the README.
Cheers,

**Comment by jonjoliver** [comment]
I do not have time to review alternative versions.
I would request that you include regression tests to confirm that results are consistent.
I will add a reference - and add a disclaimer about all 3rd party ports of TLSH
Expect this in the next release - which we are building - the current status is requesting people to test the Python version on https://test.pypi.org/project/py-tlsh/4.7.1/

**Comment by jonjoliver** [comment]
done in version 4.8.1
