### ISSUE TITLE
computing log(len) a.k.a l_capturing on large values of len

### ISSUE THREAD

**Issue by kevemueller** [trendmicro/tlsh#88]
TLSH saves an approximation of the log of the number of digested bytes in a single byte of its metadata. The algorithm to obtain the byte is presented in pseudocode in the TLSH presentation and as a commented C code in tlsh_util.cpp reference implementation.
For efficiency purposes the reference implementation uses a pre-computed list of threshold values which was derived from the C code.

### Problem
Currently the table is capped at 4GiB, mapping to byte 170. It should be made explicit, whether it is intentional that all source lengths >4GiB should map to 170 in the specification.
The single byte could, store encoded lengths of up to 12TiB.

### Recommendation
The table of thresholds should be extended for the full range of 255 length values, to map lengths between 4GiB and 12TiB as well. Lengths > 12TiB should saturate the length byte at 255.

**Comment by jonjoliver** [comment]
Release version 4.6.0 Issue 99 raised issues about what to do when evaluating the TLSH for files over 4GB We decided to define that TLSH is the TLSH of the first 4GB of a file.

So closing this issue.

We are willing to extend the definition of TLSH to optionally allow a port of TLSH to calculate the hash in a consistent way for files over 4GB.
Do you require that I add such language for your port?
Re-open this issue if you want us to make that change?

Cheers
jono
