### ISSUE TITLE
Java reference implementation miscomputes l_capturing

### ISSUE THREAD

**Issue by kevemueller** [trendmicro/tlsh#89]
Opposed to the C++ reference implementation, the Java reference implementation uses the log based formula to compute lCapturing and not a lookup.
The formula is almost verbatim the same as the C++ version, but the semantics are different.
In C++ `std::log((float) len)` picks the `float std::log(float)`, i.e. `logf` implementation, whereas in Java `Math.log` always uses `double log(double)`.
The remainder of the calculation with doubles is the same.

The subtle difference manifests itself in rounding errors at specific inputs.
E.g. for a length of 190336, the C++ version returns 65, but the Java version computes 64.
This means that the hash computed by the C++ version will be different from the hash computed by the Java version. This is undesireable.

Generally speaking, using log and calculations on float/double in the spec is questionable.

To fix the mismatch with minimum coding changes the calculation should read:
```
        double d = (float) Math.log((float) len);
        if (len <= 656) {
            d = d / LOG_1_5;
        } else if (len <= 3199) {
            d = d / LOG_1_3 - 8.72777D;
        } else {
            d = d / LOG_1_1 - 62.5472D;
        }
```
Note the truncation of the log to float and subsequent widening.

**Comment by jonjoliver** [comment]
I believe that we resolved this issue in release 4.6.0 on 23/04/2021
Please reopen if we have not addressed the issue
