### ISSUE TITLE
Python extension py2.7 compatibility

### ISSUE THREAD

**Issue by abgoldberg** [trendmicro/tlsh#95]
I noticed that the new python extension on PyPI indicates python 3.6 as a requirement, but it looks like the code technically still supports 2.7. Is this intentional, or could PyPI be updated to allow 2.7 installs? Thanks!

**Comment by jonjoliver** [comment]
Do we have to change only the lines in the package from
PKG-INFO:Requires-Python: >=3.6
setup.py:    python_requires='>=3.6',
To
PKG-INFO:Requires-Python: >=2.7
setup.py:    python_requires='>=2.7',

Or will more extensive changes be required?
If those are the only changes required, I can do that...

**Comment by abgoldberg** [comment]
Yes, I believe that is all that is needed. Thanks!

**Comment by jonjoliver** [comment]
Thanks - I will update the package in the next few days.
If you could test that it works in your Python 2 environment, then we can close the case.
Thanks again!

**Comment by jonjoliver** [comment]
I created a new Python package and updated this repo
Please check at
https://test.pypi.org/project/py-tlsh/4.7.1/
To install use
$ pip install -i https://test.pypi.org/simple/ py-tlsh==4.7.1

**Comment by jonjoliver** [comment]
Version 4.7.2 is now at https://pypi.org/project/py-tlsh/
It is working for me.
I changed the Python version required to 2.7
I added further Python Regression tests
