### ISSUE TITLE
pip install python_tlsh installs very old version ( 0.2.0)

### ISSUE THREAD

**Issue by garyhski1** [trendmicro/tlsh#96]
On ubuntu 20.04, when I do a pip install python_tlsh, I get a very old version. Can this be updated to install a more recent version by default
python3
>>> import tlsh
>>> print(tlsh.__version__)
0.2.0
When I build and install the latest from GitHub I get
4.5.0

**Comment by garyhski1** [comment]
What's installed may actually be 3.17.0 ( not 0.2.0) but I don't know how to verify that for sure

**Comment by jonjoliver** [comment]
I have updated README.md to say to use package "py-tlsh"

If you pip-install py-tlsh, then it says (in Python 3.9.0)
>>> from importlib.metadata import version
>>> version('py-tlsh')
'4.5.0'
