### ISSUE TITLE
PyPy (alternate python runtime) compatibility?

### ISSUE THREAD

**Issue by bollwyvl** [trendmicro/tlsh#98]
Hi folks, thanks for this project!

I'm an (accidental) maintainer of this downstream on [conda-forge](https://github.com/conda-forge/tlsh-feedstock) (i'm mostly interested in a _further_ downstream [diffoscope](https://github.com/conda-forge/diffoscope-feedstock), but do try to keep the ship running), and would love to be able to use it with [pypy](https://www.pypy.org/).

I have no idea at what level the incompatibility exists, and don't imagine I have the skills (or the extra bandwidth to do learn them at the moment) to offer any real insight into it, so this is _definitely_ a feature request!

Some data, though: we have two automated requests open to support [pypy36](https://github.com/conda-forge/tlsh-feedstock/pull/10) and [pypy37](https://github.com/conda-forge/tlsh-feedstock/pull/11) that fail with compiler errors I don't recognize, but perhaps spur someone's thoughts?

Semi-related:
- #95: pypy27 (which conda-forge does _not_ package) will be [supported indefinitely by the pypy upstream](https://doc.pypy.org/en/latest/faq.html#how-long-will-pypy-support-python2)
  -  i for one am not clamoring for that as a candidate, but others might have stronger feelings

**Comment by jonjoliver** [comment]
Hi Nicholas

I will try to look at this and resolve it

cheers jono

**Comment by jonjoliver** [comment]
sorry I neglected this.
I just released a new package
     $ pip install -i https://test.pypi.org/simple/ py-tlsh==4.7.0
Could you provide more details about the compiler errors/ problems you are having

**Comment by jonjoliver** [comment]
Version 4.7.2 is now at https://pypi.org/project/py-tlsh/
It is working for me.
I changed the Python version required to 2.7
I added further Python Regression tests

Could you provide more details about the compiler errors/ problems you are having

**Comment by jonjoliver** [comment]
I believe this was resolved in 4.7.2 (I have not heard anything to the contrary)
